name: Build Succesful on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: Use Node.js
        uses: action/setup-node@v3
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build-parser--prod
